# level is optional for both sinks and loggers
# level for error logging is 'error', not 'err'
# _st => single threaded, _mt => multi threaded
# syslog_sink is automatically thread-safe by default, no need for _mt suffix

# max_size supports suffix
# - T (terabyte)
# - G (gigabyte)
# - M (megabyte)
# - K (kilobyte)
# - or simply no suffix (byte)

# check out https://github.com/gabime/spdlog/wiki/3.-Custom-formatting
global_pattern = "[%Y-%m-%dT%T.%e][%L][%t][%@]%v"

[[sink]]
name = "console_st"
type = "stdout_sink_st"

[[sink]]
name = "console_mt"
type = "stdout_sink_mt"

[[sink]]
name = "color_console_st"
type = "color_stdout_sink_st"

[[sink]]
name = "color_console_mt"
type = "color_stdout_sink_mt"

[[sink]]
name = "info"
type = "scheduled_file_sink_st"
scheduled_type = "daily"
base_filename = "./logs/info.log"
# truncate field is optional
# truncate = false (default)
level = "debug"
# optional flag to indicate the set-up to create the log dir first
create_parent_dir = true

[[sink]]
name = "warn"
type = "scheduled_file_sink_st"
scheduled_type = "daily"
base_filename = "./logs/warn.log"
# truncate field is optional
# truncate = false (default)
level = "warn"
# optional flag to indicate the set-up to create the log dir first
create_parent_dir = true

[[sink]]
name = "error"
type = "scheduled_file_sink_st"
scheduled_type = "daily"
base_filename = "./logs/error.log"
# truncate field is optional
# truncate = false (default)
level = "error"
# optional flag to indicate the set-up to create the log dir first
create_parent_dir = true

[[sink]]
name = "heartb"
type = "scheduled_file_sink_st"
scheduled_type = "daily"
base_filename = "./logs/heartb.log"
level = "info"

[[pattern]]
name = "succient"
value = "%c-%L: %v"

[[logger]]
name = "default"
is_default = true
is_async = true
async.block = true 
flush_level = "error"
sinks = ["info", "warn", "error"]
level = "trace"

[[logger]]
name = "heartb"
sinks = ["heartb"]
# pattern = "succient"
flush_level = "info"
